In [1]:
import numpy as np

In [2]:
myarr=np.array([1,2,3,4,5])

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [4]:
myarr[1]

2

In [5]:
myarr.shape

(5,)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[1]=45                       #replace the value

In [8]:
myarr

array([ 1, 45,  3,  4,  5])

# Array creation: Conversion from other python structures

In [9]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({22,33,44})

array({33, 44, 22}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
rng=np.arange(12)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
lspace=np.linspace(1,5,12)

In [23]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp

array([[4.67296746e-307, 1.69121096e-306, 6.23047842e-307,
        2.22526399e-307, 6.23053614e-307, 7.56592338e-307],
       [1.60216183e-306, 7.56602523e-307, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037317e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 2.22522597e-306],
       [1.33511290e-306, 1.69118108e-306, 9.34604358e-307,
        9.34598925e-307, 1.24612081e-306, 2.22522596e-306]])

In [27]:
emp_like=np.empty_like(lspace)

In [29]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [37]:
ide=np.identity(10)

In [38]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
ide.shape

(10, 10)

In [40]:
arr= np.arange(99)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [45]:
ar=np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.sum(axis=0)

array([12,  8,  9])

In [48]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T                  # T=Transpose--- row becomes column and column becomes rows

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim              # number of dimensions

2

In [54]:
ar.size

9

In [56]:
ar.nbytes             # elements taking how many bites

36

In [57]:
one=np.array([1,2,3,4,5,6,7])

In [59]:
one.argmax()                 # gives the index value where you have maximum value

6

In [61]:
one.argmin()                  # gives the index value where you have minimum value

0

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar2= np.array([[1,2,1],[4,0,6],[8,1,0]])

In [65]:
ar +ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [66]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
import sys

In [69]:
py_ar=[1,2,3,4]

In [70]:
np_ar=np.array(py_ar)

In [71]:
sys.getsizeof(1)*len(py_ar)

112

In [72]:
np_ar.itemsize* np_ar.size

16