In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Dimensions in array

In [7]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [8]:
# 1 D array

In [10]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim) 

[1 2 3 4 5]
1


In [11]:
#2 D array

In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
#3 D array

In [15]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [16]:
# create an array with 5 dimensions and verify that it has 5 dimensions

In [22]:
arr=np.array([1,2,3,4], ndmin=5)                # create 5 dimensions
print(arr)
print('number of dimensions are:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions are: 5


In [21]:
arr=np.array([[[[[1,2,3,4]]]]])                 # create 5 dimensions
print(arr)
print('number of dimensions are:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions are: 5


In [23]:
# Numpy array indexing

In [25]:
arr=np.array([1,2,3,4,5])               
print(arr[2])                   # indexing

3


In [26]:
# find the 3rd , 6th and 8th elements and add them

In [28]:
m=np.array([5,4,3,6,8,7,9,10,34,55,23,76,58,99,100])
print('the third element is:',m[3])
print('the sixth element is:',m[5])
print('the 8th element is:',m[7])
print('sum of this elements is:',m[3]+m[5]+m[7])      
      

the third element is: 6
the sixth element is: 7
the 8th element is: 10
sum of this elements is: 23


In [29]:
#2 D indexing

In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,2])                     # 1 is the position of 2nd array[5,6,7,8]

7


In [35]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print('first element of 1st row:',arr[0,0])
print('last element of 2nd row:',arr[1,4])
print('sum is:', arr[0,0]+arr[1,4])

first element of 1st row: 10
last element of 2nd row: 100
sum is: 110


In [36]:
# Access 3 d array

In [37]:
# Access the 3rd element of the second array of the first array

In [39]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [40]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])

12
