In [1]:
#Slicing of arrays

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [5]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [6]:
# slicing in 2D array

In [8]:
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [10]:
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


In [11]:
# checking the data type of an array

In [12]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [13]:
arr=np.array(['animal','bat'])
print(arr.dtype)

<U6


In [14]:
# Creating array with a defined data type

In [15]:
arr=np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [16]:
# CREATE AN ARRAY WITH DATA TYPES 4 BYTES INTEGER

In [17]:
arr=np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [18]:
# Numpy array shapes

In [19]:
# the shape of an array is the number of elements in each dimension

In [20]:
#print the shape of 2D array

In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [22]:
arr=np.array([1,2,3,4])
print(arr.shape)

(4,)


In [23]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr.shape)

(1, 3, 4)


In [26]:
# Joining Numpy 1D array

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [27]:
# Joining Numpy 2D array

In [29]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
# splitting Numpy arrays

In [32]:
# splitting the array in 3 parts

In [33]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
# splitting the array in 4 parts

In [35]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [37]:
# ravel & faltten -- convert multidimensional array into 1D array

In [40]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('Dimension is :',m.ndim)
n=m.ravel()
print(n)
print('The new dimension is:',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is : 3
[1 2 3 4 5 6 7 8 9]
The new dimension is: 1


In [41]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('Dimension is :',m.ndim)
n=m.flatten()
print(n)
print('The new dimension is:',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is : 3
[1 2 3 4 5 6 7 8 9]
The new dimension is: 1


In [47]:
c=np.array([[[[1,2,3],[67,78,65],[23,33,43]]]])
print(c)
print('The dimension is:',c.ndim)
d=c.ravel()
print(d)
print('the new dimension is:',d.ndim)

[[[[ 1  2  3]
   [67 78 65]
   [23 33 43]]]]
The dimension is: 4
[ 1  2  3 67 78 65 23 33 43]
the new dimension is: 1


In [48]:
c=np.array([[[[1,2,3],[67,78,65],[23,33,43]]]])
print(c)
print('The dimension is:',c.ndim)
d=c.flatten()
print(d)
print('the new dimension is:',d.ndim)

[[[[ 1  2  3]
   [67 78 65]
   [23 33 43]]]]
The dimension is: 4
[ 1  2  3 67 78 65 23 33 43]
the new dimension is: 1


In [51]:
# Unique function t print the unique values\ elements

In [50]:
k=np.array([12,3,4,56,42,78,22,33,44,55,66,22,33,98,78])
print(k)
x=np.unique(k)
print(x)

[12  3  4 56 42 78 22 33 44 55 66 22 33 98 78]
[ 3  4 12 22 33 42 44 55 56 66 78 98]


In [52]:
#Delete

In [54]:
a=np.array([1,2,3,4,5,6,7])
d=np.delete(a,[1])
print(d)

[1 3 4 5 6 7]


In [56]:
x=np.array([[1,2,3,4],[5,6,7,8],[10,20,30,40]])
print(x)
m=np.delete(x,1,axis=0)
print()
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]]

[[ 1  2  3  4]
 [10 20 30 40]]
